spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: fireflyspacial@gmail.com
    password: whiskassache99!!!
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true